#lang sicp
(define (pascal-elem row col)
  (cond ((= col 1) 1)
        ((= row col) 1)
        (else (+ (pascal-elem (- row 1) (- col 1))
                 (pascal-elem (- row 1) col)))))
(define (pascal-col-iter row col)
  (display (pascal-elem row col))
  (if (> row col)
      (pascal-col-iter row (+ col 1))
      (display "\n")))
(define (pascal-row-iter row n)
  (pascal-col-iter row 1)
  (if (< row n)
      (pascal-row-iter (+ row 1) n)
      (display "")))
(define (pascal n)
  (pascal-row-iter 1 n))