#lang racket
(require sicp-pict)
(require graphics/graphics)
(open-graphics)
(define (frame-coord-map frame)
  (lambda (v)
    (add-vect
     (origin-frame frame)
     (add-vect (scale-vect (xcor-vect v)
                           (edge1-frame frame))
               (scale-vect (ycor-vect v)
                           (edge2-frame frame))))))
(define (make-frame origin edge1 edge2)
  (list origin edge1 edge2))
(define (origin-frame frame) (car frame))
(define (edge1-frame frame) (cadr frame))
(define (edge2-frame frame) (cadr (cdr frame)))
(define (make-vect x y)
  (list x y))
(define (xcor-vect vec)
  (car vec))
(define (ycor-vect vec)
  (cadr vec))
(define (add-vect vec1 vec2)
  (make-vect (+ (xcor-vect vec1)
                (xcor-vect vec2))
             (+ (ycor-vect vec1)
                (ycor-vect vec2))))
(define (sub-vect vec1 vec2)
  (make-vect (- (xcor-vect vec1)
                (xcor-vect vec2))
             (- (ycor-vect vec1)
                (ycor-vect vec2))))
(define (scale-vect n vect)
  (make-vect (* n (xcor-vect vect))
             (* n (ycor-vect vect))))
(define (for-each proc items)
  (map proc items)
  (newline))

(define (segments->painter segment-list)
  (lambda (frame)
    (for-each
     (lambda (segment)
       (draw-line
        ((frame-coord-map frame) (start-segment segment))
        ((frame-coord-map frame) (end-segment segment))))
     segment-list)))
(define (make-segment vec1 vec2)
  (list vec1 vec2))
(define (start-segment segment)
  (car segment))
(define (end-segment)
  (cadr segment))





      
