#lang sicp
(define (cons a b)
  (* (expt 2 a)
     (expt 3 b)))
(define (car cons-value)
  (define (iter i value)
    (if (= (remainder value 2) 0)
        (iter (+ 1 i) (/ value 2))
        i))
  (iter 0 cons-value))
(define (cdr cons-value)
  (define (iter i value)
    (if (= (remainder value 3) 0)
        (iter (+ 1 i) (/ value 3))
        i))
  (iter 0 cons-value))