#lang sicp
(define (encode message tree)
  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
              (encode (cdr message) tree))))
(define (element-of-set? x set)
  (cond ((null? set) false)
        ((equal? x (car set)) true)
        (else (element-of-set? x (cdr set)))))
(define (make-leaf symbol weight)
  (list 'leaf symbol weight))
(define (leaf? object)
  (eq? (car object) 'leaf))
(define (symbol-leaf x) (cadr x))
(define (weight-leaf x) (caddr x))

(define (make-code-tree left right)
  (list left
        right
        (append (symbols left) (symbols right))
        (+ (weight left) (weight right))))
(define (left-branch tree) (car tree))
(define (right-branch tree) (cadr tree))
(define (symbols tree)
  (if (leaf? tree)
      (list (symbol-leaf tree))
      (caddr tree)))
(define (weight tree)
  (if (leaf? tree)
      (weight-leaf tree)
      (cadddr tree)))
; solution
(define (encode-symbol symbol tree)
  (cond ((element-of-set? symbol (symbols (left-branch tree)))
         (if (leaf? (left-branch tree))
             (list 0)
             (cons 0 (encode-symbol symbol (left-branch tree)))))
        ((element-of-set? symbol (symbols (right-branch tree)))
         (if (leaf? (right-branch tree))
             (list 1)
             (cons 1 (encode-symbol symbol (right-branch tree)))))
        (else (error "bad symbol" symbol))))

(define sample-tree
  (make-code-tree (make-leaf 'A 4)
                  (make-code-tree
                   (make-leaf 'B 2)
                   (make-code-tree (make-leaf 'D 1)
                                   (make-leaf 'C 1)))))

;(define sample-message '(0 1 1 0 0 1 0 1 0 1 1 1 0)) ;(A D A B B C A)
(encode-symbol 'A sample-tree)
(encode-symbol 'D sample-tree)
(encode-symbol 'A sample-tree)
(encode-symbol 'B sample-tree)
(encode-symbol 'B sample-tree)
(encode-symbol 'C sample-tree)
(encode-symbol 'A sample-tree)

